# Generated by Django 3.1.6 on 2021-02-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLIKACJA', '0002_auto_20210207_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(),
        ),
    ]
