# Generated by Django 3.1.6 on 2021-02-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLIKACJA', '0003_auto_20210207_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='length_video',
            field=models.IntegerField(default=0),
        ),
    ]
