# Generated by Django 3.1.6 on 2021-02-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLIKACJA', '0004_film_length_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, upload_to='APLIKACJA/images'),
        ),
    ]
