# Generated by Django 3.1.6 on 2021-02-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLIKACJA', '0006_auto_20210207_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, upload_to='APLIKACJA/images'),
        ),
    ]
