# Generated by Django 3.1.6 on 2021-02-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLIKACJA', '0007_auto_20210207_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='youtube',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
