# Generated by Django 3.1.6 on 2021-02-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLIKACJA', '0008_auto_20210209_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating_video',
            field=models.IntegerField(default=0),
        ),
    ]
